//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPA_VIEW
    {
        public int Expr1 { get; set; }
        public string JobNo { get; set; }
        public string Expr2 { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> line_id { get; set; }
        public string MachineNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PartNo { get; set; }
        public string ProgrammerName { get; set; }
        public string DrawingRevision { get; set; }
        public string Shift { get; set; }
        public string SupervisorName { get; set; }
        public string Operation { get; set; }
        public string InspectorName { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<bool> HeatTreatmentSlugRequired { get; set; }
        public string Supervisor_sign { get; set; }
        public string prog_sign { get; set; }
        public string qi_stamp_sign { get; set; }
        public string MaterialDrawingRequired { get; set; }
        public string MaterialColorCode { get; set; }
        public string Issued_material_color_code { get; set; }
        public string IssuedMaterialPartLot { get; set; }
        public string IssuedMaterialDescription { get; set; }
        public string PartSQRNCode { get; set; }
        public Nullable<bool> mm { get; set; }
        public Nullable<bool> Inch { get; set; }
        public Nullable<bool> is_saved { get; set; }
        public Nullable<bool> IS_Delete { get; set; }
        public string ProgramUploaded { get; set; }
        public string SetupSheetUploaded { get; set; }
        public string InformationVerifiedByQI { get; set; }
        public string Dimension_Total { get; set; }
        public string Remark { get; set; }
        public string Results_by_programmer { get; set; }
        public string Results_by_inspector { get; set; }
        public string Instrument_ID { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public int ID { get; set; }
    }
}
