//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartWhse
    {
        public string Company { get; set; }
        public string PartNum { get; set; }
        public string WarehouseCode { get; set; }
        public decimal DemandQty { get; set; }
        public decimal ReservedQty { get; set; }
        public decimal AllocatedQty { get; set; }
        public decimal PickingQty { get; set; }
        public decimal PickedQty { get; set; }
        public Nullable<System.DateTime> CountedDate { get; set; }
        public decimal OnHandQty { get; set; }
        public decimal NonNettableQty { get; set; }
        public decimal BuyToOrderQty { get; set; }
        public decimal SalesDemandQty { get; set; }
        public decimal SalesReservedQty { get; set; }
        public decimal SalesAllocatedQty { get; set; }
        public decimal SalesPickingQty { get; set; }
        public decimal SalesPickedQty { get; set; }
        public decimal JobDemandQty { get; set; }
        public decimal JobReservedQty { get; set; }
        public decimal JobAllocatedQty { get; set; }
        public decimal JobPickingQty { get; set; }
        public decimal JobPickedQty { get; set; }
        public decimal UnfirmJobDemandQty { get; set; }
        public decimal TFOrdDemandQty { get; set; }
        public decimal TFOrdReservedQty { get; set; }
        public decimal TFOrdAllocatedQty { get; set; }
        public decimal TFOrdPickingQty { get; set; }
        public decimal TFOrdPickedQty { get; set; }
        public string KBCode { get; set; }
        public decimal MinimumQty { get; set; }
        public decimal MaximumQty { get; set; }
        public decimal SafetyQty { get; set; }
        public int KBPONUM { get; set; }
        public int KBPOLine { get; set; }
        public string KBWarehouseCode { get; set; }
        public string KBBinNum { get; set; }
        public string KBPlant { get; set; }
        public decimal KBQty { get; set; }
        public decimal PcntTolerance { get; set; }
        public bool CalcPcnt { get; set; }
        public bool CalcQty { get; set; }
        public bool CalcValue { get; set; }
        public decimal QtyAdjTolerance { get; set; }
        public bool CalcQtyAdj { get; set; }
        public string MinAbc { get; set; }
        public string SystemAbc { get; set; }
        public bool ManualABC { get; set; }
        public Nullable<System.DateTime> LastCCDate { get; set; }
        public bool OvrrideCountFreq { get; set; }
        public int CountFreq { get; set; }
        public decimal QtyTolerance { get; set; }
        public decimal ValueTolerance { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public int BlanketPONum { get; set; }
        public int BlanketPOLine { get; set; }
    }
}
