//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_System_Name
    {
        public int ID { get; set; }
        public Nullable<int> MID { get; set; }
        public string SystemNum { get; set; }
        public string PartNum { get; set; }
        public Nullable<int> Complexity { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Part_Type { get; set; }
        public Nullable<int> Yearly_Qty { get; set; }
        public Nullable<int> FL_Stock { get; set; }
        public Nullable<int> SN_Stock { get; set; }
        public Nullable<int> Rev { get; set; }
        public Nullable<decimal> Cycle_Time { get; set; }
    }
}
