//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Planning_Priority
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Change_Remark { get; set; }
        public Nullable<System.DateTime> Change_Date { get; set; }
        public string Change_By { get; set; }
    }
}
