//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Planning
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Machine { get; set; }
        public string Machine_name { get; set; }
        public string Machine_no { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string OP { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public Nullable<System.DateTime> Planning_start_date { get; set; }
        public Nullable<System.DateTime> Planning_end_date { get; set; }
        public string revision { get; set; }
        public string OP_Name { get; set; }
        public string status { get; set; }
        public Nullable<int> Job_Qty { get; set; }
        public Nullable<int> Ok_Qty { get; set; }
        public Nullable<int> Remaining_Qty { get; set; }
        public Nullable<decimal> Setup_time { get; set; }
        public Nullable<decimal> Cycle_Time { get; set; }
        public Nullable<int> Completed_Day { get; set; }
        public Nullable<decimal> Assigned_Qty { get; set; }
        public Nullable<System.TimeSpan> Planning_start_time { get; set; }
        public Nullable<System.TimeSpan> Planning_end_time { get; set; }
        public Nullable<System.DateTime> Setup_Date { get; set; }
        public Nullable<System.DateTime> Production_Date { get; set; }
        public Nullable<System.TimeSpan> Setup_datetime { get; set; }
        public Nullable<System.TimeSpan> Production_Time { get; set; }
        public Nullable<System.DateTime> Production_End_Date { get; set; }
        public Nullable<System.DateTime> Production_Start_Date { get; set; }
        public string System_Name { get; set; }
        public Nullable<bool> Change_Job { get; set; }
        public string Change_Remark { get; set; }
        public string Change_Jobnum { get; set; }
        public string Change_op { get; set; }
        public string Change_machine_name { get; set; }
        public Nullable<bool> Change_job_Approval { get; set; }
        public Nullable<System.DateTime> Other_Datetime { get; set; }
        public Nullable<System.DateTime> Promise_Ship_Date { get; set; }
        public Nullable<System.DateTime> Resetting_date { get; set; }
        public Nullable<System.DateTime> Production_Start_date_resetting { get; set; }
        public Nullable<bool> Force_Close { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string created_user { get; set; }
    }
}
