//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcvHead
    {
        public string Company { get; set; }
        public int VendorNum { get; set; }
        public string PurPoint { get; set; }
        public string PackSlip { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string EntryPerson { get; set; }
        public bool SaveForInvoicing { get; set; }
        public bool Invoiced { get; set; }
        public string ReceiptComment { get; set; }
        public string ReceivePerson { get; set; }
        public string ShipViaCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Plant { get; set; }
        public int PONum { get; set; }
        public string LCReference { get; set; }
        public string LCComment { get; set; }
        public decimal LandedCost { get; set; }
        public string LegalNumber { get; set; }
        public decimal LCVariance { get; set; }
        public bool ICLinked { get; set; }
        public string GlbCompany { get; set; }
        public int GlbVendorNum { get; set; }
        public string GlbPurPoint { get; set; }
        public string GlbPackSlip { get; set; }
        public int ContainerID { get; set; }
        public decimal Weight { get; set; }
        public string LCDisburseMethod { get; set; }
        public bool AutoReceipt { get; set; }
        public string AutoTranType { get; set; }
        public string POType { get; set; }
        public int AutoTranID { get; set; }
        public string WeightUOM { get; set; }
        public decimal UpliftPercent { get; set; }
        public decimal SpecDutyAmt { get; set; }
        public decimal AppliedLCAmt { get; set; }
        public decimal LCDutyAmt { get; set; }
        public decimal LCIndCost { get; set; }
        public bool ApplyToLC { get; set; }
        public bool Received { get; set; }
        public Nullable<System.DateTime> ArrivedDate { get; set; }
        public decimal AppliedRcptLCAmt { get; set; }
        public decimal LCUpliftIndCost { get; set; }
        public decimal AppliedLCVariance { get; set; }
        public string TranDocTypeID { get; set; }
        public string ImportNum { get; set; }
        public int ImportedFrom { get; set; }
        public string ImportedFromDesc { get; set; }
        public decimal GrossWeight { get; set; }
        public string GrossWeightUOM { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string TaxRegionCode { get; set; }
        public Nullable<System.DateTime> TaxPoint { get; set; }
        public Nullable<System.DateTime> TaxRateDate { get; set; }
        public bool InPrice { get; set; }
        public bool HdrTaxNoUpdt { get; set; }
        public string TaxRateGrpCode { get; set; }
        public bool TaxesCalculated { get; set; }
        public decimal InAppliedLCAmt { get; set; }
        public decimal InAppliedLCVariance { get; set; }
        public decimal InAppliedRcptLCAmt { get; set; }
        public decimal InLandedCost { get; set; }
        public decimal InLCDutyAmt { get; set; }
        public decimal InLCIndCost { get; set; }
        public decimal InLCUpliftIndCost { get; set; }
        public decimal InLCVariance { get; set; }
        public decimal InSpecDutyAmt { get; set; }
        public string CNDeclarationBill { get; set; }
        public bool CNBonded { get; set; }
        public int APTaxRoundOption { get; set; }
        public string ASNID { get; set; }
    }
}
